### ISSUE TITLE
Providing a docs edit link and last updated details.

### ISSUE THREAD

**Issue by vishakhanihore** [kubernetes-sigs/contributor-site#112]
As seen from many documentations and contributors' sites, there is a need to provide `Edit on GitHub` and `Last Updated` link from the website document to the corresponding source of truth of doc.

/cc @mrbobbytables @parispittman 
/priority important-soon
/kind feature
/assign

**Comment by mrbobbytables** [comment]
The docsy theme will provide this functionality, however it will not work with ingested content without some restructuring of the docsy theme itself.

If at some point documentation is moved to the contributor site as the primary source this should resolve itself.

**Comment by mrbobbytables** [comment]
I'm going to go ahead and close this out for now -- should the contributor documentation ever be merged into the contributor site as the source of truth we can revisit this.
/close
