### ISSUE TITLE
[docsy] SCSS generation error

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/contributor-site#123]
This is blocking the general development of the docsy site conversion:
There is an issue between netlify and hugo with builds throwing this error:
```
Error building site: TOCSS: failed to transform "scss/main.scss" (text/x-scss):
SCSS processing failed: file "stdin", line 6, col 1: File to import not found or
unreadable:  ../vendor/bootstrap/scss/bootstrap
```

This has temporarily been resolved by committing the generated resources directory in the [WIP Preview Branch](https://github.com/kubernetes-sigs/contributor-site/pull/122), however this should be resolved before the general docsy branch is updated for others to 
work off.

**Comment by miloszkowal** [comment]
What version of Hugo are you using? According to the Docsy theme, you need the `extended` version, downloadable here: https://github.com/gohugoio/hugo/releases

That being said, I'm also experiencing this error when trying to build a Docsy page myself, despite having this error.

**Comment by mrbobbytables** [comment]
Tried multiple versions from v0.65.x - v0.68.3 -- by default netlify does build with the extended version as well.

The current WIP is built with v0.68.3
https://github.com/kubernetes-sigs/contributor-site/blob/d8c818706dc9adf724ec63c5044070473a52ec81/netlify.toml#L6

**Comment by mrbobbytables** [comment]
It looks like a `package.json` file is required with at least these 2 dependencies:
```
  "dependencies": {
    "autoprefixer": "^9.7.6",
    "postcss-cli": "^7.1.0"
}
```
netlify will handle installing them before generating the site.

The current [wip](https://github.com/kubernetes-sigs/contributor-site/pull/122) is functional but needs clean up. This issue can be closed once its cleaned up and makefile updated with correct command.

**Comment by mrbobbytables** [comment]
This has now been resolved -- it's a combo problem:
1) The docsy theme itself has its own submodules that must be fetched. Hugo will throw an SCSS error if they are not found. The solution is to fetch them `git submodule update --init --recursive --depth 1`
2)  The postcss-cli and autoprefixer JavaScript packages are required. These are installed automatically by netlify but need to be installed on a person's system for it to function.

With that, going to go ahead and close this out -- the readme on the wip branch has been updated with the notes on the above.

/close
