### ISSUE TITLE
[docsy] Add contributor calendar

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/contributor-site#127]
The [calendar](https://kubernetes-contributor.netlify.com/events/community-calendar/) will have to be re-implemented under docsy once it is promoted to master.

It should now be an item listed under [resources](https://5e8a6dc2828fc70007c6208c--kubernetes-contributor.netlify.com/resources/).

**Comment by joshuabezaleel** [comment]
Hi @mrbobbytables , I found that the quickest hack to embed the calendar is just to put the GCal's url with the `<iframe>` tag and wrap it around `<div>`. Will it be an accepted solution for this issue though? 
![image](https://user-images.githubusercontent.com/7043511/83974630-0c11ef80-a919-11ea-87e2-820e505bd2c8.png)
![image](https://user-images.githubusercontent.com/7043511/83974640-1df39280-a919-11ea-9b47-4eced2def005.png)

**Comment by mrbobbytables** [comment]
I should have documented this issue a bit further >_< We'd like to re-impliment [fullcalendar](https://fullcalendar.io/) which we had with the previous iteration of the site.
Here is an older version: https://5eae09846d3a2da64be11b32--kubernetes-contributor.netlify.app/events/community-calendar/

Here is a link to the old javascript bit we had: https://github.com/kubernetes-sigs/contributor-site/blob/63ee5afd16a89934ec70c24df11a3178339e92d9/assets/js/calendar.js

Events currently aren't being displayed because of the domain name change for netlify -- I've updated the allowed URLs, but it may be a bit before they're visible.

**Comment by mrbobbytables** [comment]
The calendar has been added in https://github.com/kubernetes-sigs/contributor-site/pull/136
