### ISSUE TITLE
Participate in Season of Docs?

### ISSUE THREAD

**Issue by nikhita** [kubernetes-sigs/contributor-site#128]
Google has recently announced the 2020 version of their Google Season of Docs (GSoD) program. CNCF has applied as an organization and is participating in the program - https://github.com/cncf/mentoring/tree/master/seasonofdocs.

According to the [timeline](https://developers.google.com/season-of-docs/docs/timeline), we have until 11 May to submit project ideas. I just wanted to get the issue created to track/start the conversation around this to check if we (contributor-site subproject) want to participate in it.

cc @mrbobbytables @castrojo @idvoretskyi @zacharysarah

**Comment by zacharysarah** [comment]
@nikhita Yes we do! 💯 The program ideas there are what I’ve come up with so far. Please feel free to add or revise! 🙏

**Comment by mrbobbytables** [comment]
It has been merged \o/ 
Thanks to @zacharysarah for the last minute review :)
https://github.com/cncf/mentoring/tree/master/seasonofdocs#update-the-kubernetes-developer-guide

For now I'm going to close this out and we'll wait and see 👍 

/close
