### ISSUE TITLE
Umbrella issue for broken links

### ISSUE THREAD

**Issue by castrojo** [kubernetes-sigs/contributor-site#13]
Running a hosted 404 link checker or a CLI tool like linkchecker finds lots of 404's and out of date links on k/community.

We're going to need to sort out which ones are generator inflicted, and then which ones are just out of date/broken in the repo itself. 

We should then come up with a plan to socialize how people can help fix/update these links. This should be tied into a new contributor ramp, these are fixes that would be useful to the community and are easy enough to onramp.

**Comment by castrojo** [comment]
linkchecker reports: That's it. 420217 links in 1043 URLs checked. 1 warning found. 772 errors found.

**Comment by castrojo** [comment]
See also: https://github.com/kubernetes/community/issues/359

**Comment by mrbobbytables** [comment]
With the recent updates, we're down to a small subset of broken links with most of them tied to bad links within the community repo itself.

**Comment by mrbobbytables** [comment]
closing this as we're starting from scratch
/close
