### ISSUE TITLE
"Meet our Contributors" weird sentence

### ISSUE THREAD

**Issue by lfrancke** [kubernetes-sigs/contributor-site#130]
The [Meet our Contributors](https://github.com/kubernetes-sigs/contributor-site/blob/master/content/Events/meet-our-contributors.md) page has this sentence:

> Grab a copy of the calendar to yours from kubernetes.io/community

Something seems to be missing in that sentence.
I'm not sure what the intention was.
In addition, there's no calendar to be found at that site.

Happy to create a PR to just remove that sentence.

**Comment by mrbobbytables** [comment]
I'd update in the original document here: https://github.com/kubernetes/community/blob/master/mentoring/programs/meet-our-contributors.md

The Moc/Office Hours/Community meeting pages were copied from their locations in k/community with some things like the youtube embeds added to test some functionality of hugo.^^;;;

We'll need to update it, but that brings up a bigger question - @castrojo @parispittman should the events pages be imported from k/community with the import script? or should we keep our own copy here with things like the youtube embeds in it etc?

**Comment by lfrancke** [comment]
Thanks for the quick response.

I didn't even realize that this was just a copy.
Is it a manual or automated process? (you refer to an import script)

Shall I close this issue and open a new one in k/community?

**Comment by mrbobbytables** [comment]
The things under the events directory were manually imported to test some things.
They would be imported with the [hack/gen-content.sh](https://github.com/kubernetes-sigs/contributor-site/blob/master/hack/gen-content.sh) script if we wanted to remove things like the youtube embeds.

I'd go ahead an open up an issue in k/community, but can leave this open for now to answer these questions:
> We'll need to update it, but that brings up a bigger question - @castrojo @parispittman should the events pages be imported from k/community with the import script? or should we keep our own copy here with things like the youtube embeds in it etc?

**Comment by mrbobbytables** [comment]
Going to close this one for now since we have the open issue in k/community 👍 

/close
