### ISSUE TITLE
Sidebar nav suggested changes

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-site#14]
The sidebar navigation should have only 4-5 options and have titles changed to more umbrella like topics.

Examples:

- committee-steering should be steering commitee and be lumped under 'Governance' along with community membership, governance, and sig governance. 
- kubernetes mentoring initiative should just be mentoring
- keps should probably be spelled out 
- working groups and sigs are ultimately serving the same page (sigs list) so they should be combined with a title of 'special interest and working groups'
- communication should be 'how we communicate' which is more of a call to click then communication
- do we have to display the archive?
- should design proposals in the contributors section go under or with keps?
- the contributors umbrella should be titled contributor guide with the devel as an option under

**Comment by mrbobbytables** [comment]
closing this as we're starting from scratch
/close
