### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-site#15]
Most of the items in the events section should not be displayed here. How can we import a calendar feature? Could we generate a calendar from sigs.yaml since thats where they display the times/dates? The problem with that is hosts for those meetings won't be able to change their times if they cancel a meeting, reschedule, etc. We would also need a way to import contributor events not sig/wg meetings like the summit and meet our contributors.

**Comment by vishakhanihore** [comment]
@mrbobbytables I think this issue has been addressed in the events index PR. Or is there anything more needed to be done in this one ?

**Comment by mrbobbytables** [comment]
I think so. Eventually we will want to expand on it more for things like the contributor summits, but that's a later problem.
