### ISSUE TITLE
Automatic update of site when external content is updated

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/contributor-site#160]
Currently the site is only updated when a PR to this repo is merged or a manual trigger of a build is done in netlify. Long term a prow job should be configured to trigger the rebuild webhook whenever the externally sourced content is updated. 

As a short term solution, a periodic job could be configured to trigger rebuilding the site on something like a 12hr interval.

**Comment by kushthedude** [comment]
Hey @mrbobbytables How about having a github action for the automatic trigger?

**Comment by mrbobbytables** [comment]
@kushthedude As it spans multiple repos and they have prow in place I'd lean a bit more towards doing it that way. For the most part though it should be pretty similar :)

**Comment by kushthedude** [comment]
There is not any prow job for contributor-site right now, should I add one here https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-sigs ?

**Comment by mrbobbytables** [comment]
OOOH, I think I get what you were saying now. We could setup a github action for this repo to trigger on an interval to rebuild. 

Long term we'd want prow jobs to trigger a rebuild targeting the places where the external content is sourced:
- [kubernetes/community](https://github.com/kubernetes/community)
  - `/contributors/guide`
- [kubernetes/sig-release](https://github.com/kubernetes/sig-release)
  - `/releases`

That way the prow job would trigger a rebuild anytime content in those external sources is updates.

**Comment by kushthedude** [comment]
Yes, that was I was saying. We can setup up a cron github action to curl
the rebuild webhook at particular interval.

**Comment by sftim** [comment]
The GitHub Action trigger sounds like a reasonable idea, and would also work for https://k8s.io/ (which has similar needs).

**Comment by mrbobbytables** [comment]
I think with the action trigger in place, this is good to close 👍 

/close
