### ISSUE TITLE
Image missing in https://www.kubernetes.dev/resources/release/

### ISSUE THREAD

**Issue by dholbach** [kubernetes-sigs/contributor-site#161]
https://www.kubernetes.dev/resources/release/ include

```html
<img src="accentuate-the-pawsitive.png" height=400 width=auto>
```

Looking at https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/README.md (which is probably the source?) the original image lives at https://github.com/kubernetes/sig-release/blob/master/releases/release-1.19/accentuate-the-pawsitive.png

**Comment by castrojo** [comment]
I bet an absolute URL would work, here's a nice shorthand one: https://git.k8s.io/sig-release/releases/release-1.19/accentuate-the-pawsitive.png

**Comment by dholbach** [comment]
From https://github.com/kubernetes/sig-release/pull/1204#pullrequestreview-477868720:

> Seems like it would make more sense for the consumer to convert that link to an appropriate URL than trying to maintain it here. If other releases are going to be included on the contributor site they would also have broken image links right now. What do you think?

**Comment by mrbobbytables** [comment]
I agree with @hasheddan. We source external content through a few csv files that contain references to other repos

I opened #162 to support importing other content for the release directory.
