### ISSUE TITLE
Need a release dashboard

### ISSUE THREAD

**Issue by castrojo** [kubernetes-sigs/contributor-site#2]
We should help the release team by making contributor.k8s.io/release a useful place. 

Currently the release team uses a bit.ly link to point people to the right place. http://bit.ly/k8s112-release-info

Ideas for things to include on this page (please include more!):

- A banner up top "We are currently in: $STATE". Freeze, slush, etc. with a link to what each of those terms mean.
- A clever way to integrate the important release dates and make them obvious
- Links that show the latest development release, stable release, and older supported release version numbers, clickable to allow for driving down into release info. 
- List and contact information for each release team member for that cycle.
- Integrate the [k8s-release](https://discuss.kubernetes.io/tags/k8s-release) tag so users can see the latest announcements from the release team. 
- Shortcut links to appropriate devstats charts the team deems important. 

For now, we can just make the URL autoforward to the right place on github so we can socialize it.

**Comment by mrbobbytables** [comment]
For now I think a link a link to the current release page would be sufficient as an MVP - say for the 1.18 release cycle it'd link here:
https://git.k8s.io/sig-release/releases/release-1.18#timeline

We'd bump it to 1.19 after 1.18 is cut.

**Comment by vishakhanihore** [comment]
@mrbobbytables Rather than linking can we import the ReadME for the Release Dashboard, As it clearly contains the essentials for the release cycle ?

**Comment by mrbobbytables** [comment]
We could. I'd update the root doc to include a metadata header and weight though and that should also be something discussed with sig-release (I don't think they'd have an issue with it). My reason for originally just linking to the timeline is because that's what most folk are interested in. That being said, its easy enough to scroll down.

**Comment by mrbobbytables** [comment]
/reopen
cc @justaugustus

**Comment by mrbobbytables** [comment]
Per slack discussion (https://kubernetes.slack.com/archives/C2C40FMNF/p1580302816258200), we have the go-ahead to import the content and update the source with the metadata header.

**Comment by vishakhanihore** [comment]
I will update the doc and go ahead with the PR in here :+1:

**Comment by vishakhanihore** [comment]
For now, importing the Release Document ReadME and its content should be sufficient for contributors and visitors to get a GIST about the release cycle and process.
We can come back to this later once we have a published website to enhance and improve this section more.
