### ISSUE TITLE
Add design proposals and architecture designs

### ISSUE THREAD

**Issue by castrojo** [kubernetes-sigs/contributor-site#26]
Need to add:

- design-proposals/ (historical design proposals from https://git.k8s.io/community/contributors/design-proposals)
- arch[itecture]|design/ (design principles of Kubernetes, derived from reorganizing https://git.k8s.io/community/contributors/devel, mentioned here)

We turned these off on the contributor site because they are just a pile of markdown files with lots of broken links, etc. We'd need for these files to have frontmatter in order to render pretty.

**Comment by sftim** [comment]
also see https://github.com/kubernetes-sigs/contributor-site/issues/207
