### ISSUE TITLE
Contributing footer

### ISSUE THREAD

**Issue by castrojo** [kubernetes-sigs/contributor-site#3]
Each page should generate a link in the footer that takes the user to the right page in the community repo to submit fixes/edits.

**Comment by mrbobbytables** [comment]
For this we'll want to get a good idea of the content folder structure first. With the files are being moved around and renamed to be more site friendly, the inverse set of rules will need to be added to the footer template.

**Comment by mrbobbytables** [comment]
I gave this some thought. Probably the easiest way to go about this will be to inject the original url as a frontmatter attribute **before** reorganizing content. It means the url doesn't have to be generated following a set of reverse rules, and if content organization changes it the rules wouldn't have to be updated.

What this means work wise:
* when executing in a build context (`HUGO_BUILD=true`) it should  `git reset --hard origin/master` then fetch to work around the netlify cache issues.
* frontmatter header injection will be done in original repo and will be updated to include the original url.

**Comment by mrbobbytables** [comment]
The attribute `original_url` has been added to the frontmatter for every page. This should be doable now with updating the footer to reference that value.
