### ISSUE TITLE
display a contributors wanted dashboard

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-site#39]
have a green-yellow-red dashboard for new and current contributors to look for other sigs/wgs to join that may be actively recruiting more. sig/wg name - status light. 

Green light would be tied to having good-first-issue and/or help-wanted labels
Yellow light would be tied just help-wanted (ie - likely better for casual and other contributors with experience)
Red light would be no use of either label

**Comment by parispittman** [comment]
also have the link or display the contributor role board for the other nonGH related positions

**Comment by castrojo** [comment]
Initial PR links to the role board from the root, but perhaps something slicker and embedable. 

https://github.com/kubernetes-sigs/contributor-site/pull/50

**Comment by mrbobbytables** [comment]
I think this is fixed by linking to the role board. Going to go ahead and close.
/close
