### ISSUE TITLE
[content] contributor changelog & news

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-site#56]
can we pull in all of the changes that we are proposing and those that are landing in a contributor changelog - could use k-dev for this automation? could be a 'news' section and that's one of the sections. in a news area, could also pull in the chairs/tls email, any changes that are made to sigs.yaml (new groups, chairs, etc.).

**Comment by mrbobbytables** [comment]
I'm not sure how much we can automate with this. It's very difficult to automatically pick things that are _'news worthy'_.  As an example for picking up sigs.yaml changes, you could use git log, but the content itself would simply be the git commit messages and you'd get a mix of things like:
```
Update steering meeting time to Monday 11am PT
Add myself to the CoCC
Update reference-docs repo location
```

/remove-lifecycle stale

**Comment by parispittman** [comment]
could we automate it to the point were its a stream of things that someone can approve/reject/modify? and then it would save time manually looking at all of those places to curate something.

**Comment by parispittman** [comment]
ok then ill type up a list of things that someone will need to manually check on a weekly basis to pull in for curation
