### ISSUE TITLE
[content] Contributor Growth 

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-site#57]
A few sections for this one:

1 - introduction to the contributor ladder and owners files with a canonical link to the definitions
(this comes up several times throughout the [content strategy doc](https://docs.google.com/document/d/1_4qnfu5kNCxfO3yjaoBO6LM9KfqxGC4HnAvVakIQM-I/edit?usp=sharing); folks don't know what membership is, how to get to the next ladder, etc.) 

2 - high level summary of mentoring we offer and links to fuller descriptions

3 - known teams (release, api reviewers, etc.)

4 - embed the contributor role board?

**Comment by celanthe** [comment]
Per a conversation with @parispittman--I am going to be taking this on. :)

**Comment by celanthe** [comment]
Hi @parispittman -- Hope we can circle back on this after KubeCon when things calm down a bit. Just a note-- @mrbobbytables had mentioned that we may be able to streamline this a bit via sourcing content from other repos where we can. I would love your thoughts there.  :)

**Comment by celanthe** [comment]
Hi all, I'm going to be stepping back a bit and focusing more on the upstream marketing blog content for now, I've unassigned myself from this issue and am hopeful someone else picks it up.
