### ISSUE TITLE
[content] stuff to surface that all contributors need 

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-site#58]
Info that needs to be surfaced for everyone. 

- [ ] code of conduct, 
- [ ] link back to community site,
- [ ] contributor meetings calendar
- [ ] youtube feed for sig meetings, meet our contributors, public steering meetings, community meeting
- [ ] how we communicate/ask for help

Taking from [this doc](https://docs.google.com/document/d/1_4qnfu5kNCxfO3yjaoBO6LM9KfqxGC4HnAvVakIQM-I/edit?usp=sharing) and setting as an issue so we can close the doc down.

**Comment by celanthe** [comment]
Per a conversation with @parispittman--I am going to be taking this on. :)

**Comment by celanthe** [comment]
Hi @parispittman -- Wanted to circle back on this with yourself and maybe @mrbobbytables once things calm down a bit, see if we can hammer out some next steps. :)

**Comment by celanthe** [comment]
Hi all, I'm going to be stepping back a bit and focusing more on the upstream marketing blog content for now as I've been stretched a bit too thin, I've unassigned myself from this issue and am hopeful someone else picks it up.
