### ISSUE TITLE
[content] stuff to surface for new contributors

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-site#59]
how to get started/what sig do I join?, 
- [ ] development.md (source: survey)
- [ ] Contributor guide
- [ ] Finding issues to work on (source: survey)
- [ ] curated communication channels aimed at getting help (#pr-reviews, #meet-our-contributors, etc.)

mentoring opportunities, (source: survey, focus groups)
- [ ] Meet our contributors
- [ ] Gsoc
- [ ] Outreachy
- [ ] Contributors playground / links to the most recent recordings of new contributor workshop / links to outlines of content for ncw

Taking from [this doc](https://docs.google.com/document/d/1_4qnfu5kNCxfO3yjaoBO6LM9KfqxGC4HnAvVakIQM-I/edit?usp=sharing) and setting as an issue so we can close the doc down.

**Comment by celanthe** [comment]
Per a conversation with @parispittman--I am going to be taking this on. :)
