### ISSUE TITLE
[research] other contributor sites

### ISSUE THREAD

**Issue by parispittman** [kubernetes-sigs/contributor-site#61]
Special thanks to @jberkus for collecting this information. 

[Mozilla](https://www.mozilla.org/en-US/contribute/) - goodness included multiple paths for engagement including things like "follow us on twitter" which (AFAIC) are a lovely "stepping up" to contribution pathway; up-to-date events list; the "easy" interface here (https://www.mozilla.org/en-US/contribute/signup/); this page https://www.mozilla.org/en-US/firefox/channel/desktop/#beta (so friendly). The bad: this page (https://firefox-dev.tools/) is, I think, where the hardcore coders would start for instructions and it isn't as easy to find
[Fedora](https://whatcanidoforfedora.org/en#designexclamation) -- they loved this! For a while it was impossible to find, but now it's linked nicely from the main getfedora page (yah!)
OpenMRS has a different approach in that the have a "How to contribute" book (http://devmanual.openmrs.org/en/) but I like it because it covers a lot of the non-dev-specific things like how they work and the project history in one place (this info is avail for many projects, but it's all spread out, so it is hard to know what things you should know before you start)
[Ansible](https://docs.ansible.com/ansible/latest/community/index.html) Pretty dense, but we've built up a fair amount of process over the
years. Getting the right people the right info can be a challenge;
this is our best attempt, and it's pretty much ever-evolving. [New draft version](https://docs.ansible.com/ansible/devel/community/index.html)
Gentoo has a 'Get involved' section which itself leads to https://gentoo.org/get-involved/contribute/that explains how one can contribute to the project. Note that we don't actually have a ton of core committers but receive significant contribution on our wiki and through our proxy maintainers project and the contribution web site is meant to detail different ways folks can get involved with the project besides just writing ebuilds.
At libreoffice.org take a look at the "Improve it" menu on the top navigation bar. We've recently revamped this section of the web site, which acts as an entry point to all the various places people can engage, including the DevCentral portal https://devcentral.libreoffice.org/ and the Developers area of our wiki https://wiki.documentfoundation.org/Development
FSFE has a page at https://fsfe.org/contribute/contribute.en.html which
we have overhauled just recently. Actually we've received quite positive
feedback about it, so it might help.
also node -> https://nodejs.org/en/get-involved/contribute/

Some projects that have "contributor profile" pages. This isn't something we've discussed before; is it something we'd want to do? There is a bit of a scale problem, of course:
[Drupal](https://www.drupal.org/u/dries)
Including "[people mentored](https://www.drupal.org/user/128537/people-mentored)", which is a way to encourage mentorship
Eclipse: https://projects.eclipse.org/projects/eclipse.jdt/who
Microprofile: https://microprofile.io/contributors/
PostgreSQL: https://www.postgresql.org/community/contributors/

**Comment by mrbobbytables** [comment]
Those are good examples. I do think that to be useful to everyone we will need both a focused getting started or contributor landing page akin to the [mozilla contribute](https://www.mozilla.org/en-US/contribute/), but we will need to surface both our contributor and developer guides. They both need an overhaul in layout and organization (ref: https://github.com/kubernetes-sigs/contributor-site/issues/86, ref: https://github.com/kubernetes/community/issues/4444, ref: https://github.com/kubernetes/community/issues/3064) though.

/lifecycle frozen

**Comment by abenokraitis** [comment]
The Ansible Engineering team is currently maintaining `community.kubernetes` Collection that will also be split up soon. Let me know if you need more info.

**Comment by mrbobbytables** [comment]
With the launch of the site, I think this is safe to close.

@abenokraitis The subproject [kubespray](https://github.com/kubernetes-sigs/kubespray) uses ansible, as far as I know they're evaluating what they're going to do( https://github.com/kubernetes-sigs/kubespray/issues/6400), but any dialog about it should probably move over there 👍 I can help route to the right people if you need it.

/close
