### ISSUE TITLE
Home page needs content

### ISSUE THREAD

**Issue by cblecker** [kubernetes-sigs/contributor-site#68]
https://kubernetes-contributor.netlify.com/

cc: @parispittman

**Comment by jberkus** [comment]
This needs to start with deciding what *should* be on the home page.

My vote here is task-based navigation, e.g.:

Welcome to Kubernetes Contributors!  What are you here for?

- New to the project and wanting to learn how to contribute

- Looking up information on specific policies, procedures, and documents

- Reviewing current contributions

- Looking for articles, events, and contributor activities

**Comment by chris-short** [comment]
+1

**Comment by parispittman** [comment]
listing the what are you here for when we don't have those pages yet could get difficult - or we will need to link to the community repo. 

i would rather have a homepage that lists what we are doing with the site (goals), what people can look for in the next iteration, and a call to action of some sort. maybe pictures and friendly stuff. clean and simple. and then have the contrib guide, events, and calendar ready to go as features.

**Comment by chris-short** [comment]
If we want to surface things then perfect. But, the up next for the site itself I feel could be kept to a blog post or issues/PRs. It sounds a little under construction-y and aspirational goals aren't going to surface anything but, a project board or issue filter would.

**Comment by jberkus** [comment]
But we *do* have a lot of that information.  It's just that most of it is scattered about.

Anyway, the important question was whether task-based navigation was where we wanted to go for the home page.  Role-based navigation could also work, although I kinda feel like that'll point to a lot more material we don't already have.

I'm not keen on a home page that doesn't have immediate links to things people want to know.  I feel like if that's what we have, folks will land on the home page, then take off.

**Comment by markyjackson-taulia** [comment]
This has already been broken out and the core of this issues has been addressed

**Comment by vishakhanihore** [comment]
I suggest keeping this issue open, we will need a landing page even after
addressing sub-parts of the issues.

**Comment by mrbobbytables** [comment]
I'm going to re-close this. The landing page itself will mostly be links to other content within the contributor site itself. Which should generally be handled by the docsy theme.

/close
