### ISSUE TITLE
KEP section improvements

### ISSUE THREAD

**Issue by castrojo** [kubernetes-sigs/contributor-site#8]
We need to figure out a way to ingest KEP metadata so that we can show open keps, keps that have been implemented, etc. 

https://www.python.org/dev/peps/ wouldn't be a bad place to start inspiration-wise.

**Comment by mrbobbytables** [comment]
Just for additional information -- the KEP info page is blocked until the keps themselves are migrated and metadata made consistent. For more information, see the KEP migration umbrella Issue:  https://github.com/kubernetes/enhancements/issues/617
