### ISSUE TITLE
Revamping the Contributor Guide Section

### ISSUE THREAD

**Issue by vishakhanihore** [kubernetes-sigs/contributor-site#86]
For the first pass as we can see on https://kubernetes-contributor.netlify.com/guide/ , We have imported the complete `Community/Contributor/Guide` directory. This may be a lot to digest for a new contributor who just wants to get started with his contributions. We must revamp the current Contributor Guide getting presented as on the website into much simpler and easy to navigate.
Some of the points:-
- Mainly each contributor wants to get started with setting up the development environment & getting started with Kubernetes Workflow.
- After which he may see our Workflow & Automation to which he may navigate to First Contribution and PR section.
- We can have a link mentioning `Additional Resources` which may redirect to `contributor/guide`.

cc: @parispittman @mrbobbytables

**Comment by parispittman** [comment]
agreed that its way too much content for a single page. the pages that are to the left nav side bar are also arbitrary - I would rather those show things like 'your first contribution'.

what if it was more of a descriptive table of contents (adding a short description of what each page is/what the reader would get from it) and then links out to the respective github pages?

**Comment by mrbobbytables** [comment]
I've created a [tracking issue in k/community](https://github.com/kubernetes/community/issues/4444) for updates regarding the guide itself.

**Comment by mrbobbytables** [comment]
The sections have been updated \o/ This is good to close
/close
