### ISSUE TITLE
Setup domain (kubernetes.dev)

### ISSUE THREAD

**Issue by mrbobbytables** [kubernetes-sigs/contributor-site#98]
Thanks @mauilion we have the kubernetes.dev domain 😄 
This may need to be transferred over and managed via the [k8s.io](https://github.com/kubernetes/k8s.io) which will involve working with [wg-k8s-infra](https://github.com/kubernetes/community/tree/master/wg-k8s-infra)

/kind feature
/priority important-soon

**Comment by vishakhanihore** [comment]
So are we planning to use kubernetes.dev for the contributor site rather than https://contributors.kubernetes.io/ ?

**Comment by mrbobbytables** [comment]
Right now, yes -- we'll also be able to use the k8s.dev domain as a shortener - e.g. k8s.dev/guide/

**Comment by gkarthiks** [comment]
seems right now the `kubernetes.dev` takes to the k8s org in github

**Comment by christopherhein** [comment]
I've been getting emails about my own personal Netlify domains that anything xxx.netlify.com will change to xxx.netlify.app on April 14th, meaning anyone that has been sharing https://stupefied-goodall-e282f7.netlify.com/ that link I believe will break, is that correct?

**Comment by mrbobbytables** [comment]
They do plan to forward automatically, but long term things should change to use the .app extension.
ref: https://community.netlify.com/t/changes-coming-to-netlify-site-urls/8918

**Comment by mrbobbytables** [comment]
Final external setup of domain: https://github.com/kubernetes/k8s.io/pull/1150

Once merged, the netlify redirects will be updated here and the DNS configuration should be complete.

**Comment by mrbobbytables** [comment]
This has been done \o/
/close
